import { AutomationOption } from "@/types/automation";

export const AUTOMATION_CATALOG: AutomationOption[] = [
  {
    id: "social-media-scheduler",
    name: "Social Media Scheduling Platform",
    category: "SCHEDULING",
    description: "Automates multi-channel social post queuing, calendar scheduling, and publishing.",
    estimatedMonthlyCostMin: 1000,
    estimatedMonthlyCostMax: 2500,
    typicalTimeReductionMin: 70,
    typicalTimeReductionMax: 90,
    suitableFor: ["Social media queueing", "Calendar posting", "Content distribution"],
    limitations: ["Requires initial content creation", "Real-time engagement still needs review"],
  },
  {
    id: "appointment-scheduler",
    name: "Automated Calendar Scheduling Tool",
    category: "SCHEDULING",
    description: "Eliminates back-and-forth emails by letting clients self-book open meeting slots.",
    estimatedMonthlyCostMin: 800,
    estimatedMonthlyCostMax: 2000,
    typicalTimeReductionMin: 75,
    typicalTimeReductionMax: 90,
    suitableFor: ["Booking client appointments", "Calendar sync", "Reminder notifications"],
    limitations: ["Requires clear calendar availability rules"],
  },
  {
    id: "crm-data-automation",
    name: "CRM & Database Workflow Automation",
    category: "DATA_ENTRY_AUTOMATION",
    description: "Syncs leads, logs customer interactions, and populates database fields automatically.",
    estimatedMonthlyCostMin: 1500,
    estimatedMonthlyCostMax: 4000,
    typicalTimeReductionMin: 80,
    typicalTimeReductionMax: 95,
    suitableFor: ["CRM record updates", "Lead logging", "Spreadsheet sync"],
    limitations: ["Requires structured field mappings"],
  },
  {
    id: "invoice-processing-bot",
    name: "Invoice & Expense Processing Bot",
    category: "DOCUMENT_PROCESSING",
    description: "Parses digital invoices, extracts line items, and auto-routes for accounting entry.",
    estimatedMonthlyCostMin: 2000,
    estimatedMonthlyCostMax: 5000,
    typicalTimeReductionMin: 65,
    typicalTimeReductionMax: 85,
    suitableFor: ["Routine invoice processing", "Receipt extraction", "Accounts payable entry"],
    limitations: ["Non-standard invoice formats require exception review"],
  },
  {
    id: "document-data-extractor",
    name: "Document Parsing & OCR Engine",
    category: "DOCUMENT_PROCESSING",
    description: "Extracts structured text and data tables from PDFs, forms, and digital docs.",
    estimatedMonthlyCostMin: 1500,
    estimatedMonthlyCostMax: 3500,
    typicalTimeReductionMin: 60,
    typicalTimeReductionMax: 80,
    suitableFor: ["Form processing", "Technical documentation parsing", "PDF data extraction"],
    limitations: ["Unstructured handwriting requires human verification"],
  },
  {
    id: "customer-support-ai",
    name: "AI Customer Support Assistant",
    category: "CUSTOMER_SUPPORT",
    description: "First-pass response bot that answers FAQs, triages tickets, and drafts email responses.",
    estimatedMonthlyCostMin: 2500,
    estimatedMonthlyCostMax: 7500,
    typicalTimeReductionMin: 40,
    typicalTimeReductionMax: 70,
    suitableFor: ["Basic customer email replies", "FAQ chatbot", "Support ticket triage"],
    limitations: ["Angry or complex customer issues must escalate to human agents"],
  },
  {
    id: "report-generator-bot",
    name: "Automated Report & Analytics Generator",
    category: "WORKFLOW_AUTOMATION",
    description: "Pulls metrics from multiple APIs and compiles automated weekly/monthly summary reports.",
    estimatedMonthlyCostMin: 1200,
    estimatedMonthlyCostMax: 3000,
    typicalTimeReductionMin: 80,
    typicalTimeReductionMax: 95,
    suitableFor: ["Basic report generation", "Weekly analytics summaries", "Dashboard updates"],
    limitations: ["Qualitative executive commentary requires human input"],
  },
  {
    id: "data-entry-bot",
    name: "Robotic Process Data Entry Bot",
    category: "DATA_ENTRY_AUTOMATION",
    description: "Automates repetitive copy-paste workflows across web apps and legacy backoffice software.",
    estimatedMonthlyCostMin: 1500,
    estimatedMonthlyCostMax: 4000,
    typicalTimeReductionMin: 85,
    typicalTimeReductionMax: 95,
    suitableFor: ["Bulk data entry", "Cross-system syncing", "Form auto-filling"],
    limitations: ["System UI changes require workflow re-configuration"],
  },
  {
    id: "meeting-assistant",
    name: "AI Meeting Assistant & Transcriber",
    category: "AI_ASSISTANT",
    description: "Records, transcribes, and extracts key action items from client calls and internal meetings.",
    estimatedMonthlyCostMin: 1000,
    estimatedMonthlyCostMax: 2500,
    typicalTimeReductionMin: 30,
    typicalTimeReductionMax: 50,
    suitableFor: ["Meeting note taking", "Action item summaries", "Call recording"],
    limitations: ["Does not replace human attendance or real-time negotiation"],
  },
  {
    id: "research-synthesizer",
    name: "AI Research & Web Scraping Synthesizer",
    category: "RESEARCH",
    description: "Crawls digital sources, benchmarks industry trends, and summarizes competitor data.",
    estimatedMonthlyCostMin: 1500,
    estimatedMonthlyCostMax: 4500,
    typicalTimeReductionMin: 50,
    typicalTimeReductionMax: 75,
    suitableFor: ["Competitor research", "Industry trend benchmarking", "Data gathering"],
    limitations: ["Strategic business implications require human synthesis"],
  },
  {
    id: "payroll-outsourcing",
    name: "Specialized Payroll & Compliance Agency",
    category: "OUTSOURCING",
    description: "Full-service fractional payroll calculation, tax filing, and regulatory compliance service.",
    estimatedMonthlyCostMin: 4000,
    estimatedMonthlyCostMax: 12000,
    typicalTimeReductionMin: 70,
    typicalTimeReductionMax: 90,
    suitableFor: ["Payroll processing", "Tax compliance", "Employee benefits admin"],
    limitations: ["Requires monthly payroll data sign-off"],
  },
  {
    id: "bookkeeping-outsourcing",
    name: "Fractional Bookkeeping & Accounting Service",
    category: "OUTSOURCING",
    description: "External accounting team for ledger reconciliation, tax preparation, and financial audits.",
    estimatedMonthlyCostMin: 5000,
    estimatedMonthlyCostMax: 15000,
    typicalTimeReductionMin: 60,
    typicalTimeReductionMax: 85,
    suitableFor: ["Monthly ledger reconciliation", "Financial compliance", "Tax preparation"],
    limitations: ["Requires internal financial document submission"],
  },
  {
    id: "graphic-design-outsourcing",
    name: "On-Demand Graphic & Creative Design Agency",
    category: "OUTSOURCING",
    description: "Fractional design team for marketing graphics, campaign banners, and visual assets.",
    estimatedMonthlyCostMin: 6000,
    estimatedMonthlyCostMax: 18000,
    typicalTimeReductionMin: 50,
    typicalTimeReductionMax: 80,
    suitableFor: ["Graphic design for campaign concepts", "Video editing", "Brand asset production"],
    limitations: ["Requires clear creative brief & brand guide"],
  },
  {
    id: "content-generation-assistant",
    name: "AI Content Draft & Copywriting Assistant",
    category: "AI_ASSISTANT",
    description: "Generates initial drafts for blog posts, email copy, and marketing documentation.",
    estimatedMonthlyCostMin: 1200,
    estimatedMonthlyCostMax: 3500,
    typicalTimeReductionMin: 40,
    typicalTimeReductionMax: 65,
    suitableFor: ["First-pass drafting", "Technical documentation outlines", "Copy brainstorming"],
    limitations: ["Requires human editing and tone refinement"],
  },
  {
    id: "human-relationship-mgmt",
    name: "Human-Led Relationship & Consultation Model",
    category: "HUMAN_ONLY",
    description: "Direct human ownership for trust building, client consultation, and high-stakes negotiation.",
    estimatedMonthlyCostMin: 0,
    estimatedMonthlyCostMax: 0,
    typicalTimeReductionMin: 0,
    typicalTimeReductionMax: 10,
    suitableFor: ["Attending client meetings", "Supplier negotiations", "Field onsite visits", "Employee interviews"],
    limitations: ["Cannot be automated with software"],
  },
  {
    id: "executive-leadership",
    name: "Executive Leadership & Business Strategy",
    category: "HUMAN_ONLY",
    description: "Human strategic decision-making, vision setting, and high-stakes business leadership.",
    estimatedMonthlyCostMin: 0,
    estimatedMonthlyCostMax: 0,
    typicalTimeReductionMin: 0,
    typicalTimeReductionMax: 15,
    suitableFor: ["Strategic business decisions", "Developing marketing strategy", "Team leadership"],
    limitations: ["Requires deep domain experience and contextual intuition"],
  },
];
