import { ToolSolution } from "@/types/tools";

/**
 * NOTE ON TOOL CATALOG PRICING:
 * Catalog prices listed below are static estimated cost ranges for reference and benchmarking.
 * They should NOT be interpreted as live, real-time, or guaranteed vendor contract pricing.
 */

export const TOOL_CATALOG: ToolSolution[] = [
  {
    id: "tool-social-scheduler",
    name: "Social Media Scheduling Platform",
    category: "SCHEDULING",
    description: "Automates recurring post publishing, queue management, and multi-channel content scheduling.",
    bestFor: "Recurring social media posts and queue scheduling",
    limitations: "Human review is required for brand-sensitive, crisis, or custom responses.",
    humanOversight: "LOW",
    pricingType: "ESTIMATED",
    estimatedCostRange: "₹1,000 – ₹3,000 / month",
    keywords: ["schedule", "social", "posts", "media", "queue", "publish", "instagram", "linkedin", "twitter"],
  },
  {
    id: "tool-appointment-booking",
    name: "Appointment & Calendar Booking Tool",
    category: "SCHEDULING",
    description: "Enables self-service client appointment booking, calendar sync, and automated SMS/email reminders.",
    bestFor: "Client appointment scheduling and calendar management",
    limitations: "Requires initial integration with master calendars and service availability rules.",
    humanOversight: "LOW",
    pricingType: "ESTIMATED",
    estimatedCostRange: "₹800 – ₹2,500 / month",
    keywords: ["book", "appointment", "calendar", "schedule", "meeting", "slots", "reminder"],
  },
  {
    id: "tool-crm-workflow",
    name: "CRM Workflow & Lead Tracking System",
    category: "CRM",
    description: "Automates lead capture, contact record updates, deal stage progression, and pipeline tracking.",
    bestFor: "CRM record entry, lead management, and pipeline tracking",
    limitations: "Data quality depends on initial field mapping and input validation rules.",
    humanOversight: "MEDIUM",
    pricingType: "ESTIMATED",
    estimatedCostRange: "₹2,000 – ₹7,000 / month",
    keywords: ["crm", "lead", "record", "contact", "pipeline", "deal", "sales", "customer"],
  },
  {
    id: "tool-customer-support-desk",
    name: "AI Customer Support & Helpdesk Desk",
    category: "CUSTOMER_SUPPORT",
    description: "Centralizes incoming support queries, auto-categorizes tickets, and drafts initial AI responses.",
    bestFor: "First-line customer inquiry triage and routine ticket drafting",
    limitations: "Complex complaints, refund requests, and billing disputes require human review.",
    humanOversight: "MEDIUM",
    pricingType: "ESTIMATED",
    estimatedCostRange: "₹2,500 – ₹8,000 / month",
    keywords: ["customer", "support", "email", "ticket", "reply", "helpdesk", "inquiry", "chat", "inbound"],
  },
  {
    id: "tool-invoice-ocr-processor",
    name: "Invoice & Expense OCR Processing Software",
    category: "INVOICING",
    description: "Extracts line items, vendor details, and totals from PDF invoices automatically for ledger entry.",
    bestFor: "Routine invoice data extraction and accounting ledger posting",
    limitations: "High-value invoices and line-item discrepancies must be approved by accounting staff.",
    humanOversight: "MEDIUM",
    pricingType: "ESTIMATED",
    estimatedCostRange: "₹1,500 – ₹5,000 / month",
    keywords: ["invoice", "invoicing", "ocr", "receipt", "expense", "bill", "accounting", "ledger"],
  },
  {
    id: "tool-payroll-service-provider",
    name: "Managed Payroll & Compliance Service",
    category: "PAYROLL",
    description: "Fractional or fully-managed payroll processing, tax filing, and employee disbursement compliance.",
    bestFor: "Monthly payroll calculation, tax withholding, and statutory compliance",
    limitations: "Internal HR sign-off and executive disbursement authorization are mandatory.",
    humanOversight: "HIGH",
    pricingType: "CUSTOM",
    estimatedCostRange: "₹3,000 – ₹12,000 / month",
    keywords: ["payroll", "tax", "disbursement", "salary", "compliance", "employee", "statutory"],
  },
  {
    id: "tool-email-sequence-automation",
    name: "Email Drip & Campaign Automation Tool",
    category: "EMAIL_AUTOMATION",
    description: "Triggers automated email drip campaigns, follow-up sequences, and customer onboarding journeys.",
    bestFor: "Outbound drip sequences, automated follow-ups, and newsletter delivery",
    limitations: "Unsubscribe management and spam-filter monitoring require ongoing oversight.",
    humanOversight: "LOW",
    pricingType: "ESTIMATED",
    estimatedCostRange: "₹1,200 – ₹4,000 / month",
    keywords: ["email", "sequence", "drip", "campaign", "follow-up", "newsletter", "outbound"],
  },
  {
    id: "tool-meeting-transcription-assistant",
    name: "AI Meeting Recorder & Transcription Assistant",
    category: "MEETING",
    description: "Captures audio from online meetings, generates transcripts, and summarizes key action items.",
    bestFor: "Documenting client meetings, internal syncs, and interview notes",
    limitations: "Human presence is required to conduct the actual conversation and negotiate terms.",
    humanOversight: "HIGH",
    pricingType: "ESTIMATED",
    estimatedCostRange: "₹1,000 – ₹3,000 / month",
    keywords: ["meeting", "attend", "transcript", "recording", "notes", "action items", "call", "zoom", "interview"],
    isHumanSupportOnly: true,
  },
  {
    id: "tool-doc-generation-platform",
    name: "Document Generation & Template Automation",
    category: "DOCUMENTATION",
    description: "Fills standardized document templates (SOPs, quotes, NDA contracts) with structured database inputs.",
    bestFor: "Technical documentation, contract templates, and standard report generation",
    limitations: "Custom legal clauses or technical specs require subject-matter expert sign-off.",
    humanOversight: "MEDIUM",
    pricingType: "ESTIMATED",
    estimatedCostRange: "₹1,500 – ₹4,500 / month",
    keywords: ["document", "documentation", "template", "sop", "contract", "technical", "report"],
  },
  {
    id: "tool-project-workflow-automation",
    name: "Project Task & Workflow Automation Hub",
    category: "PROJECT_MANAGEMENT",
    description: "Connects cross-tool apps to auto-create project tasks, sync status changes, and assign deadlines.",
    bestFor: "Task assignment, cross-app workflow triggers, and milestone updates",
    limitations: "Complex task dependencies and resource reallocation require human project manager oversight.",
    humanOversight: "LOW",
    pricingType: "ESTIMATED",
    estimatedCostRange: "₹1,500 – ₹5,000 / month",
    keywords: ["project", "workflow", "task", "management", "board", "milestone", "track"],
  },
  {
    id: "tool-marketing-analytics-dashboard",
    name: "Marketing Analytics & Reporting Dashboard",
    category: "MARKETING",
    description: "Consolidates multi-platform ad performance, social reach, and web analytics into unified reports.",
    bestFor: "Campaign performance tracking, ad reporting, and basic analytics",
    limitations: "Strategic interpretation and budget reallocation decisions remain human responsibilities.",
    humanOversight: "MEDIUM",
    pricingType: "ESTIMATED",
    estimatedCostRange: "₹2,000 – ₹6,000 / month",
    keywords: ["marketing", "campaign", "analytics", "reporting", "dashboard", "ad", "metrics", "strategy"],
  },
  {
    id: "tool-data-entry-etl",
    name: "Automated Data Import & Spreadsheet Sync",
    category: "DATA_ENTRY",
    description: "Pulls structured data from emails/webforms and syncs directly into spreadsheets and databases.",
    bestFor: "Repetitive data entry, CSV imports, and batch spreadsheet updates",
    limitations: "Data schema changes require manual rule reconfiguration.",
    humanOversight: "LOW",
    pricingType: "ESTIMATED",
    estimatedCostRange: "₹800 – ₹3,000 / month",
    keywords: ["data", "entry", "spreadsheet", "excel", "csv", "records", "import", "batch"],
  },
  {
    id: "tool-executive-bi-dashboard",
    name: "Business Intelligence & BI Reporting Engine",
    category: "ANALYTICS",
    description: "Builds real-time financial dashboards, KPI performance charts, and operational summary reports.",
    bestFor: "Basic report generation, executive dashboards, and KPI tracking",
    limitations: "Qualitative business decisions and strategy choices require leadership judgment.",
    humanOversight: "MEDIUM",
    pricingType: "ESTIMATED",
    estimatedCostRange: "₹3,000 – ₹10,000 / month",
    keywords: ["report", "generation", "bi", "analytics", "kpi", "dashboard", "metrics", "decisions"],
  },
  {
    id: "tool-hr-applicant-screener",
    name: "Recruitment & Candidate Screening Platform",
    category: "HR",
    description: "Parses inbound resumes, matches skill keywords against job criteria, and schedules interviews.",
    bestFor: "Resume screening, applicant sorting, and interview scheduling",
    limitations: "Final candidate hiring decisions and behavioral evaluation require human interviewers.",
    humanOversight: "HIGH",
    pricingType: "ESTIMATED",
    estimatedCostRange: "₹2,500 – ₹8,000 / month",
    keywords: ["hr", "employee", "interview", "recruitment", "resume", "candidate", "hiring", "applicant"],
    isHumanSupportOnly: true,
  },
  {
    id: "tool-graphic-design-suite",
    name: "AI-Assisted Graphic & Asset Creation Tool",
    category: "DESIGN",
    description: "Provides templates, AI image generation, and layout tools for digital marketing collateral.",
    bestFor: "Social media graphics, ad campaign concepts, and presentation decks",
    limitations: "Brand guideline alignment and creative direction require human designer approval.",
    humanOversight: "MEDIUM",
    pricingType: "ESTIMATED",
    estimatedCostRange: "₹1,000 – ₹4,000 / month",
    keywords: ["graphic", "design", "creative", "banner", "campaign", "image", "asset", "concept"],
  },
  {
    id: "tool-ai-content-assistant",
    name: "AI Copywriting & Research Assistant",
    category: "CONTENT",
    description: "Generates draft articles, competitor summaries, social captions, and market research outlines.",
    bestFor: "Competitor research, content drafting, and copy brainstorming",
    limitations: "Fact-checking, tone adjustments, and final publication sign-off require human editors.",
    humanOversight: "MEDIUM",
    pricingType: "ESTIMATED",
    estimatedCostRange: "₹1,200 – ₹3,500 / month",
    keywords: ["content", "research", "competitor", "copy", "writing", "draft", "article"],
  },
  {
    id: "tool-outsourced-bpo-agency",
    name: "Outsourced Back-Office & BPO Support Agency",
    category: "OUTSOURCING",
    description: "Provides dedicated third-party staff for operational tasks, customer support, and administrative execution.",
    bestFor: "Delegating high-volume operational workflows and specialized external execution",
    limitations: "Requires vendor management, defined SLAs, and internal quality checkpoints.",
    humanOversight: "HIGH",
    pricingType: "CUSTOM",
    estimatedCostRange: "Custom pricing",
    keywords: ["outsource", "bpo", "vendor", "external", "contractor", "agency", "third-party"],
  },
  {
    id: "tool-contract-negotiation-workspace",
    name: "Vendor Management & Contract Repository",
    category: "DOCUMENTATION",
    description: "Centralizes supplier agreements, terms tracking, renewal dates, and negotiation history notes.",
    bestFor: "Managing supplier contracts, term tracking, and negotiation preparation",
    limitations: "Live supplier negotiation and deal closing require direct human executive ownership.",
    humanOversight: "HIGH",
    pricingType: "CUSTOM",
    estimatedCostRange: "₹2,500 – ₹7,000 / month",
    keywords: ["negotiate", "suppliers", "vendor", "contract", "deals", "agreements"],
    isHumanSupportOnly: true,
  },
  {
    id: "tool-social-comment-moderator",
    name: "Automated Social Comment & Spam Moderation Filter",
    category: "CUSTOMER_SUPPORT",
    description: "Scans social media comments to filter spam, detect sentiment, and flag sensitive posts for review.",
    bestFor: "Social media comment moderation and sentiment tracking",
    limitations: "Nuanced, sarcastic, or crisis comments must be handled by human moderators.",
    humanOversight: "MEDIUM",
    pricingType: "ESTIMATED",
    estimatedCostRange: "₹1,000 – ₹3,000 / month",
    keywords: ["social", "comment", "moderation", "filter", "spam", "community"],
  },
  {
    id: "tool-refund-approval-portal",
    name: "Refund Triage & Audit Portal",
    category: "INVOICING",
    description: "Aggregates customer refund requests, checks store policies, and stages requests for manager approval.",
    bestFor: "Staging refund requests and checking policy eligibility",
    limitations: "Final financial refund approval requires direct human authorization due to fraud risk.",
    humanOversight: "HIGH",
    pricingType: "ESTIMATED",
    estimatedCostRange: "₹1,800 – ₹5,000 / month",
    keywords: ["refund", "approve", "dispute", "return", "financial", "authorization"],
  },
  {
    id: "tool-onsite-field-service-app",
    name: "Field Service & Dispatch Management App",
    category: "PROJECT_MANAGEMENT",
    description: "Schedules technician routes, tracks field locations, and logs on-site job completion details.",
    bestFor: "Field dispatching and route logging for physical customer visits",
    limitations: "The actual customer visit and physical service must be conducted by human personnel.",
    humanOversight: "HIGH",
    pricingType: "ESTIMATED",
    estimatedCostRange: "₹1,500 – ₹4,500 / month",
    keywords: ["visit", "onsite", "field", "customer", "dispatch", "route", "physical"],
    isHumanSupportOnly: true,
  },
  {
    id: "tool-strategic-decision-matrix",
    name: "Decision Support & Scenario Analysis Tool",
    category: "ANALYTICS",
    description: "Structures strategic decision matrices, financial forecasts, and risk evaluation scenarios.",
    bestFor: "Structuring data inputs for executive decision-making",
    limitations: "Strategic business decisions remain 100% human leadership responsibilities.",
    humanOversight: "HIGH",
    pricingType: "CUSTOM",
    estimatedCostRange: "Custom pricing",
    keywords: ["strategic", "business", "decisions", "strategy", "matrix", "leadership", "executive"],
    isHumanSupportOnly: true,
  },
  {
    id: "tool-general-workflow-automation",
    name: "General Task & Process Integration Platform",
    category: "PROJECT_MANAGEMENT",
    description: "Versatile process automation tool for triggering webhooks, data syncs, and multi-step tasks.",
    bestFor: "Connecting general software applications and automating custom repetitive tasks",
    limitations: "Requires custom setup and routine monitoring of API connections.",
    humanOversight: "MEDIUM",
    pricingType: "ESTIMATED",
    estimatedCostRange: "₹1,000 – ₹4,000 / month",
    keywords: ["automation", "general", "process", "integration", "webhook"],
  },
];
